### PR TITLE
[test] adding the construct test for the transformer

### PR DESCRIPTION
**Pull request by JiahaoYao**
this pr is to add the test for the transformer construction. 

@ggoldsh

### CODE REVIEW

**Comment by JiahaoYao** [comment]
As a side note, the zero initialization error is related to this issue #104

**Comment by ggoldsh** [comment]
Hm can you add more detail in the code here about why it doesn't work? I get that we've specially handled the zeros and ones initializers but not sure why this would break things.

**Comment by ggoldsh** [comment]
Woops didn't mean to close PR - reopened it. See comment above though.

**Comment by JiahaoYao** [comment]
not sure the reason but close this pr at this moment.

**Pull request closed without merging**
